import{R as b}from"./assets/vendor-B9UgUhXA.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))u(n);new MutationObserver(n=>{for(const r of n)if(r.type==="childList")for(const m of r.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&u(m)}).observe(document,{childList:!0,subtree:!0});function s(n){const r={};return n.integrity&&(r.integrity=n.integrity),n.referrerPolicy&&(r.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?r.credentials="include":n.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(n){if(n.ep)return;n.ep=!0;const r=s(n);fetch(n.href,r)}})();const g=document.querySelector(".shop-list"),h=[{id:1,name:"Skip animation",description:"Skips slots animation",price:50}];function S({name:t,description:e,price:s}){return`
              <li class="shop-item">
            <h2 class="item-title">${t}</h2>
            <p class="item-desc">${e}</p>
            <p class="item-price">$${s}</p>
            <button type="button">Buy</button>
          </li>
    `}function x(t){return t.map(S).join("")}function k(t){const e=x(t);g.innerHTML=e}k(h);const C=new b,O=[{symbol:"🪙",weight:3},{symbol:"🍒",weight:3},{symbol:"🍋",weight:3},{symbol:"⭐",weight:2},{symbol:"💵",weight:2},{symbol:"7️⃣",weight:1},{symbol:"🔔",weight:3}],p=document.querySelector(".number-of-spins");let c=JSON.parse(localStorage.getItem("numberOfSpins"))||0;p.textContent=c;const l={slot1:document.querySelector(".slot1"),slot2:document.querySelector(".slot2"),slot3:document.querySelector(".slot3")},a=document.querySelector(".spin-button"),i=document.querySelector(".text"),f=document.querySelector(".money-display-number");let o=parseFloat(JSON.parse(localStorage.getItem("money")))||100;f.textContent=o.toFixed(2);const d=[];let y=0;function w(){d.length=0;let t=0;O.forEach(e=>{const s={symbol:e.symbol,start:t,end:t+e.weight-1};d.push(s),t+=e.weight}),y=t}w();a.addEventListener("click",t=>{if(c++,p.textContent=c,localStorage.setItem("numberOfSpins",JSON.stringify(c)),o<1){i.textContent="Not enough money!";return}a.setAttribute("disabled",""),o-=1,Object.keys(l).forEach((e,s)=>{setTimeout(()=>{l[e].textContent=N()},200*s)}),setTimeout(()=>{a.removeAttribute("disabled","");let e=o;q(),L(e),c%10===0&&(i.textContent+=`
 Bonus Spin! 🎁 +1`,setTimeout(()=>{a.click()},100))},210*3)});function L(t){let e=o-t;e>0?i.textContent+=` (+$${e.toFixed(2)})`:e===0?i.textContent+=" (No win)":i.textContent+=" (-$1.00 spin)"}function q(){const t=l.slot1.textContent,e=l.slot2.textContent,s=l.slot3.textContent;if(t===e&&e===s){switch(t){case"🪙":o+=5;break;case"🍒":o+=3;break;case"🍋":o+=2;break;case"⭐":o+=4;break;case"💵":o+=25;break;case"7️⃣":o*=3;break;case"🔔":o+=3;break}i.textContent="You won!"}else if(t===e||e===s||t===s){switch(e===s?e:t){case"🪙":o+=2;break;case"🍒":o+=1.5;break;case"🍋":o+=1;break;case"⭐":o+=2;break;case"💵":o+=10;break;case"7️⃣":o*=1.5;break;case"🔔":o+=1;break}i.textContent="So close!"}else o+=.2,i.textContent="Better luck next time!";localStorage.setItem("money",JSON.stringify(o.toFixed(2))),f.textContent=o.toFixed(2)}function N(){const t=C.integer(0,y-1);return d.find(e=>e.start<=t&&e.end>=t).symbol}document.addEventListener("DOMContentLoaded",()=>{const t=document.querySelector(".shop-button"),e=document.querySelector(".shop");t.addEventListener("click",()=>{e.classList.toggle("open")})});
//# sourceMappingURL=index.js.map
